local Plug = vim.fn['plug#']

vim.call('plug#begin')

Plug('nvim-tree/nvim-web-devicons')
Plug('nvim-treesitter/nvim-treesitter')
Plug('neovim/nvim-lspconfig')
Plug('nvim-lua/plenary.nvim')
Plug('nvim-telescope/telescope.nvim')
Plug('nvim-telescope/telescope-file-browser.nvim')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/nvim-cmp')
Plug('hrsh7th/cmp-vsnip')
Plug('hrsh7th/vim-vsnip')
Plug('RaafatTurki/hex.nvim')
Plug('bluz71/vim-nightfly-colors')
Plug('HiPhish/rainbow-delimiters.nvim')
Plug('johnfrankmorgan/whitespace.nvim')
Plug('bluz71/nvim-linefly')
Plug('aserowy/tmux.nvim')
Plug('kdheepak/lazygit.nvim')
Plug('mbbill/undotree')
Plug('lewis6991/gitsigns.nvim')
Plug('lervag/vimtex')
Plug('kdheepak/cmp-latex-symbols')
Plug('iamcco/markdown-preview.nvim', { ['do'] = function()
    vim.fn['mkdp#util#install']()
end, ['for'] = {'markdown', 'vim-plug'}})
Plug('ravibrock/spellwarn.nvim')
Plug('petertriho/nvim-scrollbar')
Plug('kevinhwang91/nvim-hlslens')
Plug('ralex2304/verilog-autoinst.nvim', { ['branch'] = 'Treesitter-node-types-fix' })
Plug('mhinz/vim-startify', {['branch'] = 'center'})
Plug('folke/trouble.nvim')
Plug('folke/todo-comments.nvim')
Plug('sindrets/diffview.nvim')
Plug('tikhomirov/vim-glsl')

vim.call('plug#end')

require("config")
require("config_lsp")
require("config_telescope")
require("config_cmp")
require("config_theme")
require("config_homepage")
require("config_whitespace")
require("config_undotree")
require("config_linefly")
require("config_hex")
require("config_gitsigns")
require("config_tmux")
require("config_tex")
require("config_spell")
require("config_scrollbar")
require("config_hlslens")
require("config_verilog_autoinst")
require("config_trouble")
require("config_todo")
require("config_diffview")
